[tool]
[tool.poetry]
name = "UnusUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy SiriUserBot to Heroku"
authors = ["FrukanN <frukan@unususerbot.ml>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
